### ISSUE TITLE
The withMethods for Collection types should take a Collection instead of List, Set etc.

### ISSUE THREAD

**Issue by postnord-maun300** [thirdteeth/immutables-pcollections#1]
Is it possible to make it generate with-methods that takes a Collection instead of for instance a List. Now it generates:
public ImmutableTask withItemIds(List<String> list) 

It would be great if it generated this instead:
public ImmutableTask withItemIds(Collection<String> list)

**Comment by thirdteeth** [comment]
yes, I publish a new version to support this soon

**Comment by thirdteeth** [comment]
published, please use 0.1.3 version

**Comment by postnord-maun300** [comment]
Great!

Best regards
Markus
